### PR TITLE
Add dependabot.yml for dependency version updates

### PR DESCRIPTION
**Pull request by kanwalpreetd**
### What

Adding base config for `dependabot.yml`, which enables automatic PRs for [dependency version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) through Dependabot. This base config sets version updates to run on a `weekly` schedule, groups PRs for version updates, and sets max PRs that Dependabot can create for version updates  per package-ecosystem. 
But if you would like, several config options can be added to `dependabot.yml` as per [configuration-options-for-the-dependabot.yml-file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) to customize version updates, such as:

- Group PRs for version updates by [different criteria](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)
- Set [reviewers](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#reviewers) for Dependabot version updates PRs
- Etc.

Also, automatic PRs for [security updates](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/about-dependabot-security-updates) through Dependabot are already enabled through a global setting. PRs for security updates will be grouped as much as possible across directories and per ecosystem through the global setting ([grouping-dependabot-security-updates](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#grouping-dependabot-security-updates-into-a-single-pull-request)). But `dependabot.yml` can also be used for more granular security updates settings in addition to version updates (some of the options in `dependabot.yml` are shared across security and version updates), such as:

- Grouping security updates according to custom criteria: [overriding-the-default-behavior-with-a-configuration-file](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file)
- Etc.

### Why

To enable using the latest package versions, and provide a way to customize Dependabot security updates PRs.

### Known limitations

N/A

### CODE REVIEW

**Comment by Ifropc** [comment]
In this project and anchor platform we are using `gradle/libs.versions.toml` file to store dependencies and their versions. Do you know if dependabot supports this structure?

**Comment by kanwalpreetd** [comment]
@Ifropc I think I checked when creating this PR, don't think it picked up `gradle/libs.versions.toml`. But I will check again shortly.

**Comment by kanwalpreetd** [comment]
@Ifropc It should work now for `gradle/libs.versions.toml` too (there was an issue with the path when I tried earlier, it wanted me to reference the base dir even though the file is under `gradle/`, usually that's not the case for other build systems)

**Comment by Ifropc** [comment]
Thanks @kanwalpreetd let's try merging it and see how it works

**Review by Ifropc — APPROVED** [review]

**Comment by kanwalpreetd** [comment]
thanks, looks like it's working as intended. (as mentioned above, feel free to adjust the config further through: [configuration-options-for-the-dependabot.yml-file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)

**Pull request merged**
